### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#4662]
After updating my system, presumably because of numpy-1.24.0, all of the `execute_check_output` tests are failing with
```
Traceback (most recent call last):
  File "/home/wthrowe/spectre/tools/CheckOutputFiles.py", line 88, in check_h5_file
    if (test_data.dtype == np.dtype(np.float) or
  File "/usr/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
```

**Comment by nilsvu** [comment]
This is fixed here (already in a PR): https://github.com/sxs-collaboration/spectre/pull/4635/commits/07403f25a6335af8660d964325fe4e49f7c545f3

Feel free to cherry-pick the commit into any other PR you like to merge first.
