### ISSUE TITLE
Render1D - TypeError: Context.__init__() got an unexpected keyword argument 'help_option_name'

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#4961]
```
$ LD_PRELOAD=/usr/lib64/libjemalloc.so.2 bin/Render1D --help
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/wthrowe/spectre-work/bin/python/spectre/Visualization/Render1D.py", line 420, in <module>
    render_1d_command(help_option_name=["-h", "--help"])
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python3.10/site-packages/click/core.py", line 915, in make_context
    ctx = self.context_class(
TypeError: Context.__init__() got an unexpected keyword argument 'help_option_name'
```

BuildInfo.txt:
```
SpECTRE Version: 2023.04.07
Git description: v2023.04.07-38-g012f53e1f4
Git branch: predictor-corrector
Git hash: 012f53e1f4909f2f181c969c033b2fa871fadc15
Hostname: ungoliant
Host system: Linux-5.15.88-gentoo
Host system version: 5.15.88-gentoo
Host system processor: x86_64
Boost version: 1.81.0
Charm++ version: 7.0.0
CHARM_COMPILER: /usr/bin/charmc
CHARM_SHARED_LIBS: ON
CHARM_BUILDING_BLOCKS:
CHARM_CC='x86_64-pc-linux-gnu-gcc'
CHARM_CXX='x86_64-pc-linux-gnu-g++'
CHARM_LD='gcc'
CHARM_LDXX='g++'
CHARM_CC_FLAGS=' -DCMK_GFORTRAN -DCMK_GFORTRAN -D_REENTRANT -I/usr/include/charm -D__CHARMC__=1 -fno-stack-protector '
CHARM_CXX_FLAGS=' -DCMK_GFORTRAN -DCMK_GFORTRAN -D_REENTRANT -I/usr/include/charm -D__CHARMC__=1 -fno-stack-protector -fno-lifetime-dse -std=gnu++11 '
CHARM_LD_FLAGS=' -D_REENTRANT -rdynamic -Wl,-rpath,/usr/lib64/charm/lib_so/ -L/usr/lib64/charm/lib_so -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-default -lldb-rand -lconverse -lpthread -lckqt -lckqt -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /usr/lib64/charm/lib/conv-static.o'
CHARM_LDXX_FLAGS=' -D_REENTRANT -rdynamic -Wl,-rpath,/usr/lib64/charm/lib_so/ -L/usr/lib64/charm/lib_so -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-default -lldb-rand -lconverse -lpthread -lckqt -lckqt -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /usr/lib64/charm/lib/conv-static.o'
CHARMBIN='/usr/bin'
CHARMINC='/usr/include/charm'
CHARMLIB='/usr/lib64/charm/lib'
CHARMLIBSO='/usr/lib64/charm/lib_so'
BLAS_LIBRARIES: /usr/lib64/libblas.so
LAPACK_LIBRARIES: /usr/lib64/liblapack.so;/usr/lib64/libblas.so
LIBXSMM version: 1.16.1
Blaze version: 3.8
Google Benchmark found
GSL version: 2.7.1
HDF5 version: 1.12.2
jemalloc version: ..
Catch version: 2.13.8
NumPy version: 1.24.2
CMake version: 3.25.3
CMAKE_CXX_FLAGS: -fPIC -fdiagnostics-color=always -ferror-limit=1 -ftemplate-backtrace-limit=0 -gdwarf-4 -march=native
CMAKE_CXX_LINK_FLAGS:  -fuse-ld=gold
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: -fPIC -march=native
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: -march=native
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: -Wno-unused-command-line-argument -march=native -no-pie
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/lib/llvm/15/bin/clang++-15
CMAKE_CXX_COMPILER_VERSION: 15.0.7
CMAKE_C_COMPILER: /usr/lib/llvm/15/bin/clang-15
CMAKE_C_COMPILER_VERSION: 15.0.7
CMAKE_Fortran_COMPILER: /usr/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 12.2.1
Python version: 3.10.10
```

**Comment by nilsvu** [comment]
Mostly this seems to be an outdated symlink in your build directory: The `bin/Render1D` symlink doesn't exist anymore since #4548. Try `bin/spectre render-1d --help` instead (no `LD_PRELOAD` or anything like that should be necessary). However, running the Py script by itself should also work, and there's indeed a bug (fixed in https://github.com/sxs-collaboration/spectre/pull/4963), so thanks for finding it.

**Comment by wthrowe** [comment]
Must be left over from before the interface rewrite.  I haven't wiped this build directory in a while.  Using `bin/spectre render-1d` works, and your PR fixes the old symlink as well.
