### ISSUE TITLE
AttributeError: Module 'scipy' has no attribute 'ndim'

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#5828]
After upgrading to scipy 1.12:
```
$ bin/Test_Framework Unit.Pypp
Filters: "Unit.Pypp"
Randomness seeded to: 2899446833
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/scipy/__init__.py", line 137, in __getattr__
    return globals()[name]
           ~~~~~~~~~^^^^^^
KeyError: 'ndim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/scipy/__init__.py", line 139, in __getattr__
    raise AttributeError(
AttributeError: Module 'scipy' has no attribute 'ndim'

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Test_Framework is a Catch2 v3.5.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Unit.Pypp
-------------------------------------------------------------------------------
/home/wthrowe/spectre/tests/Unit/Framework/Tests/Test_Pypp.cpp:653
...............................................................................

/home/wthrowe/spectre/tests/Unit/Framework/Tests/Test_Pypp.cpp:657: FAILED:
  CHECK( (pypp::call<size_t>("scipy", "ndim", tnsr::abcc<double, 3>{})) == 4 )
due to unexpected exception with messages:
  Testing scipy support
  Could not find python function in module.

===============================================================================
test cases:   1 |   0 passed | 1 failed
assertions: 190 | 189 passed | 1 failed
```

No other tests seem to be affected.

**Comment by wthrowe** [comment]
Fixed in #5962
