### ISSUE TITLE
Segfault in support.Pipelines.Bbh.Inspiral

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#6168]
Seen in clang-14 release CI build for #6056 
```
2024-07-19T20:33:07.7745745Z test_cli (__main__.TestInspiral) ... WARNING:spectre.Pipelines.Bbh.InitialData:The BBH pipeline is still experimental. Please review the generated input files.
2024-07-19T20:33:07.7750899Z DEBUG:spectre.Pipelines.Bbh.InitialData:Initial data parameters: {
2024-07-19T20:33:07.7752169Z     'MassRight': 0.6,
2024-07-19T20:33:07.7752742Z     'MassLeft': 0.4,
2024-07-19T20:33:07.7753269Z     'XRight': 8.0,
2024-07-19T20:33:07.7753896Z     'XLeft': -12.0,
2024-07-19T20:33:07.7754550Z     'ExcisionRadiusRight': np.float64(1.116),
2024-07-19T20:33:07.7755512Z     'ExcisionRadiusLeft': np.float64(0.7440000000000001),
2024-07-19T20:33:07.7756407Z     'OrbitalAngularVelocity': 0.01,
2024-07-19T20:33:07.7757178Z     'RadialExpansionVelocity': -1e-05,
2024-07-19T20:33:07.7758031Z     'DimensionlessSpinRight_x': np.float64(0.0),
2024-07-19T20:33:07.7758957Z     'DimensionlessSpinRight_y': np.float64(0.0),
2024-07-19T20:33:07.7759916Z     'DimensionlessSpinRight_z': np.float64(0.0),
2024-07-19T20:33:07.7760831Z     'DimensionlessSpinLeft_x': np.float64(0.0),
2024-07-19T20:33:07.7761741Z     'DimensionlessSpinLeft_y': np.float64(0.0),
2024-07-19T20:33:07.7762619Z     'DimensionlessSpinLeft_z': np.float64(0.0),
2024-07-19T20:33:07.7764124Z     'HorizonRotationRight_x': np.float64(-0.0),
2024-07-19T20:33:07.7765014Z     'HorizonRotationRight_y': np.float64(-0.0),
2024-07-19T20:33:07.7765893Z     'HorizonRotationRight_z': np.float64(0.01),
2024-07-19T20:33:07.7766757Z     'HorizonRotationLeft_x': np.float64(-0.0),
2024-07-19T20:33:07.7767623Z     'HorizonRotationLeft_y': np.float64(-0.0),
2024-07-19T20:33:07.7768477Z     'HorizonRotationLeft_z': np.float64(0.01),
2024-07-19T20:33:07.7769409Z     'FalloffWidthRight': np.float64(6.479672589667676),
2024-07-19T20:33:07.7770378Z     'FalloffWidthLeft': np.float64(5.520327410332324),
2024-07-19T20:33:07.7771150Z     'L': 1,
2024-07-19T20:33:07.7771597Z     'P': 5
2024-07-19T20:33:07.7771985Z }
2024-07-19T20:33:07.7772933Z DEBUG:spectre.support.Schedule:Resolving executable: /__w/spectre/spectre/build/bin/SolveXcts
2024-07-19T20:33:07.7774685Z INFO:spectre.support.Schedule:Running with executable: /__w/spectre/spectre/build/bin/SolveXcts
2024-07-19T20:33:07.7776989Z INFO:spectre.support.Schedule:Configure run directory '/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID'
2024-07-19T20:33:07.7780145Z DEBUG:spectre.support.Schedule:Configure input file template '/__w/spectre/spectre/build/bin/python/spectre/Pipelines/Bbh/InitialData.yaml' with these parameters: {
2024-07-19T20:33:07.7783094Z     'input_file_template': PosixPath('/__w/spectre/spectre/build/bin/python/spectre/Pipelines/Bbh/InitialData.yaml'),
2024-07-19T20:33:07.7784780Z     'executable': '/__w/spectre/spectre/build/bin/SolveXcts',
2024-07-19T20:33:07.7786318Z     'run_dir': PosixPath('/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID'),
2024-07-19T20:33:07.7787696Z     'input_file_name': 'InitialData.yaml',
2024-07-19T20:33:07.7788480Z     'submit_script_name': 'Submit.sh',
2024-07-19T20:33:07.7789230Z     'out_file_name': 'spectre.out',
2024-07-19T20:33:07.7790029Z     'context_file_name': 'SchedulerContext.yaml',
2024-07-19T20:33:07.7790808Z     'submit': False,
2024-07-19T20:33:07.7791372Z     'clean_output': False,
2024-07-19T20:33:07.7791946Z     'force': False,
2024-07-19T20:33:07.7792467Z     'MassRight': 0.6,
2024-07-19T20:33:07.7792996Z     'MassLeft': 0.4,
2024-07-19T20:33:07.7793515Z     'XRight': 8.0,
2024-07-19T20:33:07.7794019Z     'XLeft': -12.0,
2024-07-19T20:33:07.7794667Z     'ExcisionRadiusRight': np.float64(1.116),
2024-07-19T20:33:07.7795605Z     'ExcisionRadiusLeft': np.float64(0.7440000000000001),
2024-07-19T20:33:07.7796491Z     'OrbitalAngularVelocity': 0.01,
2024-07-19T20:33:07.7797250Z     'RadialExpansionVelocity': -1e-05,
2024-07-19T20:33:07.7798087Z     'DimensionlessSpinRight_x': np.float64(0.0),
2024-07-19T20:33:07.7798990Z     'DimensionlessSpinRight_y': np.float64(0.0),
2024-07-19T20:33:07.7799879Z     'DimensionlessSpinRight_z': np.float64(0.0),
2024-07-19T20:33:07.7801027Z     'DimensionlessSpinLeft_x': np.float64(0.0),
2024-07-19T20:33:07.7801936Z     'DimensionlessSpinLeft_y': np.float64(0.0),
2024-07-19T20:33:07.7802812Z     'DimensionlessSpinLeft_z': np.float64(0.0),
2024-07-19T20:33:07.7803865Z     'HorizonRotationRight_x': np.float64(-0.0),
2024-07-19T20:33:07.7804720Z     'HorizonRotationRight_y': np.float64(-0.0),
2024-07-19T20:33:07.7805578Z     'HorizonRotationRight_z': np.float64(0.01),
2024-07-19T20:33:07.7806442Z     'HorizonRotationLeft_x': np.float64(-0.0),
2024-07-19T20:33:07.7807300Z     'HorizonRotationLeft_y': np.float64(-0.0),
2024-07-19T20:33:07.7808151Z     'HorizonRotationLeft_z': np.float64(0.01),
2024-07-19T20:33:07.7809049Z     'FalloffWidthRight': np.float64(6.479672589667676),
2024-07-19T20:33:07.7810001Z     'FalloffWidthLeft': np.float64(5.520327410332324),
2024-07-19T20:33:07.7810767Z     'L': 1,
2024-07-19T20:33:07.7811205Z     'P': 5,
2024-07-19T20:33:07.7811669Z     'control': False,
2024-07-19T20:33:07.7812191Z     'evolve': False,
2024-07-19T20:33:07.7812776Z     'executable_name': 'SolveXcts',
2024-07-19T20:33:07.7813467Z     'job_name': 'SolveXcts',
2024-07-19T20:33:07.7814909Z     'out_file': PosixPath('/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID/spectre.out'),
2024-07-19T20:33:07.7816654Z     'input_file': 'InitialData.yaml'
2024-07-19T20:33:07.7817254Z }
2024-07-19T20:33:07.7818631Z DEBUG:spectre.support.Schedule:Write file: /__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID/InitialData.yaml
2024-07-19T20:33:07.7821599Z INFO:spectre.support.Schedule:Run 'SolveXcts' in '/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID' on all available cores.
2024-07-19T20:33:07.7825525Z DEBUG:spectre.support.Schedule:Run command: ['/__w/spectre/spectre/build/bin/SolveXcts', '--input-file', '/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID/InitialData.yaml', '+auto-provision']
2024-07-19T20:33:07.7828249Z DEBUG:spectre.support.Schedule:'1' is an int
2024-07-19T20:33:07.7829803Z WARNING:spectre.Pipelines.Bbh.Inspiral:The BBH pipeline is still experimental. Please review the generated input files.
2024-07-19T20:33:07.7831498Z DEBUG:spectre.Pipelines.Bbh.Inspiral:Inspiral parameters: {
2024-07-19T20:33:07.7833202Z     'IdFileGlob': '/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID/BbhVolume*.h5',
2024-07-19T20:33:07.7834594Z     'ExcisionRadiusA': 1.116,
2024-07-19T20:33:07.7835277Z     'ExcisionRadiusB': 0.7440000000000001,
2024-07-19T20:33:07.7835967Z     'XCoordA': 8.0,
2024-07-19T20:33:07.7836480Z     'XCoordB': -12.0,
2024-07-19T20:33:07.7837069Z     'InitialAngularVelocity': 0.01,
2024-07-19T20:33:07.7837816Z     'RadialExpansionVelocity': -1e-05,
2024-07-19T20:33:07.7839246Z     'HorizonsFile': '/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/Horizons.h5',
2024-07-19T20:33:07.7840647Z     'AhASubfileName': 'AhA/Coefficients',
2024-07-19T20:33:07.7841432Z     'AhBSubfileName': 'AhB/Coefficients',
2024-07-19T20:33:07.7842172Z     'ExcisionAShapeMass': 0.6,
2024-07-19T20:33:07.7842840Z     'ExcisionAShapeSpin_x': 0.0,
2024-07-19T20:33:07.7844036Z     'ExcisionAShapeSpin_y': 0.0,
2024-07-19T20:33:07.7844737Z     'ExcisionAShapeSpin_z': 0.0,
2024-07-19T20:33:07.7845421Z     'ExcisionBShapeMass': 0.4,
2024-07-19T20:33:07.7846074Z     'ExcisionBShapeSpin_x': 0.0,
2024-07-19T20:33:07.7846752Z     'ExcisionBShapeSpin_y': 0.0,
2024-07-19T20:33:07.7847425Z     'ExcisionBShapeSpin_z': 0.0,
2024-07-19T20:33:07.7848025Z     'L': 1,
2024-07-19T20:33:07.7848449Z     'P': 5,
2024-07-19T20:33:07.7848997Z     'Gamma0Constant': np.float64(0.0005),
2024-07-19T20:33:07.7849798Z     'Gamma0LeftAmplitude': np.float64(4.0),
2024-07-19T20:33:07.7850601Z     'Gamma0LeftWidth': np.float64(7.0),
2024-07-19T20:33:07.7851401Z     'Gamma0RightAmplitude': np.float64(4.0),
2024-07-19T20:33:07.7852203Z     'Gamma0RightWidth': np.float64(7.0),
2024-07-19T20:33:07.7853030Z     'Gamma0OriginAmplitude': np.float64(0.0375),
2024-07-19T20:33:07.7854115Z     'Gamma0OriginWidth': 50.0,
2024-07-19T20:33:07.7854766Z     'Gamma1Width': 200.0,
2024-07-19T20:33:07.7855378Z     'MaxDampingTimescale': 20.0,
2024-07-19T20:33:07.7856089Z     'KinematicTimescale': np.float64(0.4),
2024-07-19T20:33:07.7856971Z     'SizeATimescale': np.float64(0.04000000000000001),
2024-07-19T20:33:07.7857902Z     'SizeBTimescale': np.float64(0.04000000000000001),
2024-07-19T20:33:07.7858735Z     'ShapeATimescale': np.float64(2.0),
2024-07-19T20:33:07.7859485Z     'ShapeBTimescale': np.float64(2.0),
2024-07-19T20:33:07.7860219Z     'SizeIncreaseThreshold': 0.001,
2024-07-19T20:33:07.7860975Z     'DecreaseThreshold': np.float64(0.0001),
2024-07-19T20:33:07.7861798Z     'IncreaseThreshold': np.float64(2.5e-05),
2024-07-19T20:33:07.7862545Z     'SizeBMaxTimescale': 20,
2024-07-19T20:33:07.7863159Z     'SizeAMaxTimescale': 20
2024-07-19T20:33:07.7863657Z }
2024-07-19T20:33:07.7864679Z DEBUG:spectre.support.Schedule:Resolving executable: /__w/spectre/spectre/build/bin/EvolveGhBinaryBlackHole
2024-07-19T20:33:07.7866475Z INFO:spectre.support.Schedule:Running with executable: /__w/spectre/spectre/build/bin/EvolveGhBinaryBlackHole
2024-07-19T20:33:07.7868703Z INFO:spectre.support.Schedule:Configure run directory '/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/Inspiral/Segment_0000'
2024-07-19T20:33:07.7871654Z DEBUG:spectre.support.Schedule:Configure input file template '/__w/spectre/spectre/build/bin/python/spectre/Pipelines/Bbh/Inspiral.yaml' with these parameters: {
2024-07-19T20:33:07.7874260Z     'input_file_template': PosixPath('/__w/spectre/spectre/build/bin/python/spectre/Pipelines/Bbh/Inspiral.yaml'),
2024-07-19T20:33:07.7875544Z     'no_schedule': True,
2024-07-19T20:33:07.7876418Z     'executable': '/__w/spectre/spectre/build/bin/EvolveGhBinaryBlackHole',
2024-07-19T20:33:07.7878063Z     'segments_dir': PosixPath('/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/Inspiral'),
2024-07-19T20:33:07.7879395Z     'input_file_name': 'Inspiral.yaml',
2024-07-19T20:33:07.7880096Z     'submit_script_name': 'Submit.sh',
2024-07-19T20:33:07.7880780Z     'out_file_name': 'spectre.out',
2024-07-19T20:33:07.7881498Z     'context_file_name': 'SchedulerContext.yaml',
2024-07-19T20:33:07.7882212Z     'submit': False,
2024-07-19T20:33:07.7882720Z     'clean_output': False,
2024-07-19T20:33:07.7883371Z     'force': False,
2024-07-19T20:33:07.7884383Z     'IdFileGlob': '/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID/BbhVolume*.h5',
2024-07-19T20:33:07.7885572Z     'ExcisionRadiusA': 1.116,
2024-07-19T20:33:07.7886214Z     'ExcisionRadiusB': 0.7440000000000001,
2024-07-19T20:33:07.7886871Z     'XCoordA': 8.0,
2024-07-19T20:33:07.7887350Z     'XCoordB': -12.0,
2024-07-19T20:33:07.7887893Z     'InitialAngularVelocity': 0.01,
2024-07-19T20:33:07.7888537Z     'RadialExpansionVelocity': -1e-05,
2024-07-19T20:33:07.7889634Z     'HorizonsFile': '/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/Horizons.h5',
2024-07-19T20:33:07.7890687Z     'AhASubfileName': 'AhA/Coefficients',
2024-07-19T20:33:07.7891308Z     'AhBSubfileName': 'AhB/Coefficients',
2024-07-19T20:33:07.7891906Z     'ExcisionAShapeMass': 0.6,
2024-07-19T20:33:07.7892462Z     'ExcisionAShapeSpin_x': 0.0,
2024-07-19T20:33:07.7893034Z     'ExcisionAShapeSpin_y': 0.0,
2024-07-19T20:33:07.7893567Z     'ExcisionAShapeSpin_z': 0.0,
2024-07-19T20:33:07.7894115Z     'ExcisionBShapeMass': 0.4,
2024-07-19T20:33:07.7894651Z     'ExcisionBShapeSpin_x': 0.0,
2024-07-19T20:33:07.7895203Z     'ExcisionBShapeSpin_y': 0.0,
2024-07-19T20:33:07.7895762Z     'ExcisionBShapeSpin_z': 0.0,
2024-07-19T20:33:07.7896316Z     'L': 1,
2024-07-19T20:33:07.7896718Z     'P': 5,
2024-07-19T20:33:07.7897212Z     'Gamma0Constant': np.float64(0.0005),
2024-07-19T20:33:07.7897947Z     'Gamma0LeftAmplitude': np.float64(4.0),
2024-07-19T20:33:07.7898683Z     'Gamma0LeftWidth': np.float64(7.0),
2024-07-19T20:33:07.7899424Z     'Gamma0RightAmplitude': np.float64(4.0),
2024-07-19T20:33:07.7900446Z     'Gamma0RightWidth': np.float64(7.0),
2024-07-19T20:33:07.7901229Z     'Gamma0OriginAmplitude': np.float64(0.0375),
2024-07-19T20:33:07.7901934Z     'Gamma0OriginWidth': 50.0,
2024-07-19T20:33:07.7902480Z     'Gamma1Width': 200.0,
2024-07-19T20:33:07.7903009Z     'MaxDampingTimescale': 20.0,
2024-07-19T20:33:07.7903605Z     'KinematicTimescale': np.float64(0.4),
2024-07-19T20:33:07.7904313Z     'SizeATimescale': np.float64(0.04000000000000001),
2024-07-19T20:33:07.7905223Z     'SizeBTimescale': np.float64(0.04000000000000001),
2024-07-19T20:33:07.7906060Z     'ShapeATimescale': np.float64(2.0),
2024-07-19T20:33:07.7906816Z     'ShapeBTimescale': np.float64(2.0),
2024-07-19T20:33:07.7907551Z     'SizeIncreaseThreshold': 0.001,
2024-07-19T20:33:07.7908311Z     'DecreaseThreshold': np.float64(0.0001),
2024-07-19T20:33:07.7909147Z     'IncreaseThreshold': np.float64(2.5e-05),
2024-07-19T20:33:07.7909918Z     'SizeBMaxTimescale': 20,
2024-07-19T20:33:07.7910554Z     'SizeAMaxTimescale': 20,
2024-07-19T20:33:07.7911138Z     'num_nodes': 1,
2024-07-19T20:33:07.7911707Z     'continue_with_ringdown': False,
2024-07-19T20:33:07.7912511Z     'executable_name': 'EvolveGhBinaryBlackHole',
2024-07-19T20:33:07.7913370Z     'job_name': 'EvolveGhBinaryBlackHole',
2024-07-19T20:33:07.7915330Z     'run_dir': PosixPath('/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/Inspiral/Segment_0000'),
2024-07-19T20:33:07.7917917Z     'out_file': PosixPath('/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/Inspiral/Segment_0000/spectre.out'),
2024-07-19T20:33:07.7919589Z     'input_file': 'Inspiral.yaml'
2024-07-19T20:33:07.7920143Z }
2024-07-19T20:33:07.7921631Z DEBUG:spectre.support.Schedule:Write file: /__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/Inspiral/Segment_0000/Inspiral.yaml
2024-07-19T20:33:07.7924010Z DEBUG:spectre.tools.ValidateInputFile:------------- Processor 0 Exiting: Caught Signal ------------
2024-07-19T20:33:07.7925003Z Reason: Segmentation fault
2024-07-19T20:33:07.7925769Z --------------------------------------------------------------------------
2024-07-19T20:33:07.7926831Z MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
2024-07-19T20:33:07.7927773Z with errorcode 1.
2024-07-19T20:33:07.7928054Z 
2024-07-19T20:33:07.7928469Z NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
2024-07-19T20:33:07.7929535Z You may or may not see output from other processes, depending on
2024-07-19T20:33:07.7930377Z exactly when Open MPI kills them.
2024-07-19T20:33:07.7931157Z --------------------------------------------------------------------------
2024-07-19T20:33:07.7931724Z 
2024-07-19T20:33:07.7931863Z ERROR
2024-07-19T20:33:07.7933417Z test_inspiral_parameters (__main__.TestInspiral) ... WARNING:spectre.Pipelines.Bbh.InitialData:The BBH pipeline is still experimental. Please review the generated input files.
2024-07-19T20:33:07.7935458Z DEBUG:spectre.Pipelines.Bbh.InitialData:Initial data parameters: {
2024-07-19T20:33:07.7936369Z     'MassRight': 0.6,
2024-07-19T20:33:07.7936866Z     'MassLeft': 0.4,
2024-07-19T20:33:07.7937345Z     'XRight': 8.0,
2024-07-19T20:33:07.7937807Z     'XLeft': -12.0,
2024-07-19T20:33:07.7938387Z     'ExcisionRadiusRight': np.float64(1.116),
2024-07-19T20:33:07.7939265Z     'ExcisionRadiusLeft': np.float64(0.7440000000000001),
2024-07-19T20:33:07.7940075Z     'OrbitalAngularVelocity': 0.01,
2024-07-19T20:33:07.7940766Z     'RadialExpansionVelocity': -1e-05,
2024-07-19T20:33:07.7941519Z     'DimensionlessSpinRight_x': np.float64(0.0),
2024-07-19T20:33:07.7942329Z     'DimensionlessSpinRight_y': np.float64(0.0),
2024-07-19T20:33:07.7943111Z     'DimensionlessSpinRight_z': np.float64(0.0),
2024-07-19T20:33:07.7943853Z     'DimensionlessSpinLeft_x': np.float64(0.0),
2024-07-19T20:33:07.7944581Z     'DimensionlessSpinLeft_y': np.float64(0.0),
2024-07-19T20:33:07.7945289Z     'DimensionlessSpinLeft_z': np.float64(0.0),
2024-07-19T20:33:07.7946126Z     'HorizonRotationRight_x': np.float64(-0.0),
2024-07-19T20:33:07.7947232Z     'HorizonRotationRight_y': np.float64(-0.0),
2024-07-19T20:33:07.7948098Z     'HorizonRotationRight_z': np.float64(0.01),
2024-07-19T20:33:07.7948953Z     'HorizonRotationLeft_x': np.float64(-0.0),
2024-07-19T20:33:07.7949814Z     'HorizonRotationLeft_y': np.float64(-0.0),
2024-07-19T20:33:07.7950663Z     'HorizonRotationLeft_z': np.float64(0.01),
2024-07-19T20:33:07.7951566Z     'FalloffWidthRight': np.float64(6.479672589667676),
2024-07-19T20:33:07.7952510Z     'FalloffWidthLeft': np.float64(5.520327410332324),
2024-07-19T20:33:07.7953277Z     'L': 1,
2024-07-19T20:33:07.7953718Z     'P': 5
2024-07-19T20:33:07.7954106Z }
2024-07-19T20:33:07.7955027Z DEBUG:spectre.support.Schedule:Resolving executable: /__w/spectre/spectre/build/bin/SolveXcts
2024-07-19T20:33:07.7956733Z INFO:spectre.support.Schedule:Running with executable: /__w/spectre/spectre/build/bin/SolveXcts
2024-07-19T20:33:07.7958977Z INFO:spectre.support.Schedule:Configure run directory '/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID'
2024-07-19T20:33:07.7962018Z DEBUG:spectre.support.Schedule:Configure input file template '/__w/spectre/spectre/build/bin/python/spectre/Pipelines/Bbh/InitialData.yaml' with these parameters: {
2024-07-19T20:33:07.7965083Z     'input_file_template': PosixPath('/__w/spectre/spectre/build/bin/python/spectre/Pipelines/Bbh/InitialData.yaml'),
2024-07-19T20:33:07.7966505Z     'executable': '/__w/spectre/spectre/build/bin/SolveXcts',
2024-07-19T20:33:07.7967908Z     'run_dir': PosixPath('/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID'),
2024-07-19T20:33:07.7969149Z     'input_file_name': 'InitialData.yaml',
2024-07-19T20:33:07.7969870Z     'submit_script_name': 'Submit.sh',
2024-07-19T20:33:07.7970549Z     'out_file_name': 'spectre.out',
2024-07-19T20:33:07.7971281Z     'context_file_name': 'SchedulerContext.yaml',
2024-07-19T20:33:07.7971987Z     'submit': False,
2024-07-19T20:33:07.7972481Z     'clean_output': False,
2024-07-19T20:33:07.7973001Z     'force': False,
2024-07-19T20:33:07.7973483Z     'MassRight': 0.6,
2024-07-19T20:33:07.7973982Z     'MassLeft': 0.4,
2024-07-19T20:33:07.7974456Z     'XRight': 8.0,
2024-07-19T20:33:07.7974914Z     'XLeft': -12.0,
2024-07-19T20:33:07.7975500Z     'ExcisionRadiusRight': np.float64(1.116),
2024-07-19T20:33:07.7976358Z     'ExcisionRadiusLeft': np.float64(0.7440000000000001),
2024-07-19T20:33:07.7977169Z     'OrbitalAngularVelocity': 0.01,
2024-07-19T20:33:07.7977860Z     'RadialExpansionVelocity': -1e-05,
2024-07-19T20:33:07.7978613Z     'DimensionlessSpinRight_x': np.float64(0.0),
2024-07-19T20:33:07.7979434Z     'DimensionlessSpinRight_y': np.float64(0.0),
2024-07-19T20:33:07.7980247Z     'DimensionlessSpinRight_z': np.float64(0.0),
2024-07-19T20:33:07.7981047Z     'DimensionlessSpinLeft_x': np.float64(0.0),
2024-07-19T20:33:07.7981840Z     'DimensionlessSpinLeft_y': np.float64(0.0),
2024-07-19T20:33:07.7982613Z     'DimensionlessSpinLeft_z': np.float64(0.0),
2024-07-19T20:33:07.7983382Z     'HorizonRotationRight_x': np.float64(-0.0),
2024-07-19T20:33:07.7984127Z     'HorizonRotationRight_y': np.float64(-0.0),
2024-07-19T20:33:07.7984839Z     'HorizonRotationRight_z': np.float64(0.01),
2024-07-19T20:33:07.7985540Z     'HorizonRotationLeft_x': np.float64(-0.0),
2024-07-19T20:33:07.7986327Z     'HorizonRotationLeft_y': np.float64(-0.0),
2024-07-19T20:33:07.7987176Z     'HorizonRotationLeft_z': np.float64(0.01),
2024-07-19T20:33:07.7988084Z     'FalloffWidthRight': np.float64(6.479672589667676),
2024-07-19T20:33:07.7989036Z     'FalloffWidthLeft': np.float64(5.520327410332324),
2024-07-19T20:33:07.7989794Z     'L': 1,
2024-07-19T20:33:07.7990216Z     'P': 5,
2024-07-19T20:33:07.7990671Z     'control': False,
2024-07-19T20:33:07.7991190Z     'evolve': False,
2024-07-19T20:33:07.7991760Z     'executable_name': 'SolveXcts',
2024-07-19T20:33:07.7992433Z     'job_name': 'SolveXcts',
2024-07-19T20:33:07.7993849Z     'out_file': PosixPath('/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID/spectre.out'),
2024-07-19T20:33:07.7995543Z     'input_file': 'InitialData.yaml'
2024-07-19T20:33:07.7996152Z }
2024-07-19T20:33:07.7997510Z DEBUG:spectre.support.Schedule:Write file: /__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID/InitialData.yaml
2024-07-19T20:33:07.8000400Z INFO:spectre.support.Schedule:Run 'SolveXcts' in '/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID' on all available cores.
2024-07-19T20:33:07.8004161Z DEBUG:spectre.support.Schedule:Run command: ['/__w/spectre/spectre/build/bin/SolveXcts', '--input-file', '/__w/spectre/spectre/build/tests/Unit/support/Pipelines/Bbh/Inspiral/ID/InitialData.yaml', '+auto-provision']
2024-07-19T20:33:07.8006246Z ok
2024-07-19T20:33:07.8006437Z 
2024-07-19T20:33:07.8006646Z ======================================================================
2024-07-19T20:33:07.8007355Z ERROR: test_cli (__main__.TestInspiral)
2024-07-19T20:33:07.8008212Z ----------------------------------------------------------------------
2024-07-19T20:33:07.8008989Z Traceback (most recent call last):
2024-07-19T20:33:07.8010138Z   File "/__w/spectre/spectre/tests/support/Pipelines/Bbh/Test_Inspiral.py", line 134, in test_cli
2024-07-19T20:33:07.8011328Z     start_inspiral_command(
2024-07-19T20:33:07.8012695Z   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
2024-07-19T20:33:07.8013775Z     return self.main(*args, **kwargs)
2024-07-19T20:33:07.8014891Z   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
2024-07-19T20:33:07.8015903Z     rv = self.invoke(ctx)
2024-07-19T20:33:07.8016926Z   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
2024-07-19T20:33:07.8018047Z     return ctx.invoke(self.callback, **ctx.params)
2024-07-19T20:33:07.8019265Z   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
2024-07-19T20:33:07.8020310Z     return __callback(*args, **kwargs)
2024-07-19T20:33:07.8021500Z   File "/__w/spectre/spectre/build/bin/python/spectre/support/Schedule.py", line 951, in wrapper
2024-07-19T20:33:07.8022684Z     return f(*args, **kwargs)
2024-07-19T20:33:07.8024039Z   File "/__w/spectre/spectre/build/bin/python/spectre/Pipelines/Bbh/Inspiral.py", line 473, in start_inspiral_command
2024-07-19T20:33:07.8025487Z     start_inspiral(**kwargs)
2024-07-19T20:33:07.8026793Z   File "/__w/spectre/spectre/build/bin/python/spectre/Pipelines/Bbh/Inspiral.py", line 368, in start_inspiral
2024-07-19T20:33:07.8028134Z     return schedule(
2024-07-19T20:33:07.8029154Z   File "/__w/spectre/spectre/build/bin/python/spectre/support/Schedule.py", line 545, in schedule
2024-07-19T20:33:07.8030341Z     validate_input_file(
2024-07-19T20:33:07.8031649Z   File "/__w/spectre/spectre/build/bin/python/spectre/tools/ValidateInputFile.py", line 149, in validate_input_file
2024-07-19T20:33:07.8033047Z     raise error
2024-07-19T20:33:07.8034360Z spectre.tools.ValidateInputFile.InvalidInputFileError: ------------- Processor 0 Exiting: Caught Signal ------------
2024-07-19T20:33:07.8035710Z Reason: Segmentation fault
2024-07-19T20:33:07.8036458Z --------------------------------------------------------------------------
2024-07-19T20:33:07.8037550Z MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
2024-07-19T20:33:07.8038509Z with errorcode 1.
2024-07-19T20:33:07.8038793Z 
2024-07-19T20:33:07.8039230Z NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
2024-07-19T20:33:07.8040328Z You may or may not see output from other processes, depending on
2024-07-19T20:33:07.8041194Z exactly when Open MPI kills them.
2024-07-19T20:33:07.8042001Z --------------------------------------------------------------------------
2024-07-19T20:33:07.8042579Z 
2024-07-19T20:33:07.8042962Z ----------------------------------------------------------------------
2024-07-19T20:33:07.8043846Z Ran 2 tests in 9.106s
2024-07-19T20:33:07.8044157Z 
2024-07-19T20:33:07.8044332Z FAILED (errors=1)
```

It is not clear to me from the error message what executable segfaulted.

**Comment by nilsvu** [comment]
Must be `EvolveGhBinaryBlackHole` but I wouldn't know why
